/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmbc_av_jni_ImageFormatUtils */

#ifndef _Included_com_cmbc_av_jni_ImageFormatUtils
#define _Included_com_cmbc_av_jni_ImageFormatUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    RGBAToNV21
 * Signature: ([BIII[B)V
 */
JNIEXPORT void JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_RGBAToNV21
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jbyteArray);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    rgbaToNV21
 * Signature: ([BII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_rgbaToNV21
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    scaleNV21
 * Signature: ([BII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_scaleNV21
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
