/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmbc_av_jni_ImageFormatUtils */

#ifndef _Included_com_cmbc_av_jni_ImageFormatUtils
#define _Included_com_cmbc_av_jni_ImageFormatUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    testAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_testAdd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    getNV21
 * Signature: (II[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_getNV21
  (JNIEnv *, jclass, jint, jint, jintArray);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    rgbaToYuv
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_rgbaToYuv
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    RGBAToARGB
 * Signature: ([BI[BIII)V
 */
JNIEXPORT void JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_RGBAToARGB
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    ARGBToNV21
 * Signature: ([BIII[B[B)V
 */
JNIEXPORT void JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_ARGBToNV21
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    ARGBIntToNV21
 * Signature: ([IIII[B[B)V
 */
JNIEXPORT void JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_ARGBIntToNV21
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    I420ToRgba
 * Signature: (I[B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_I420ToRgba
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    rgbToYuv
 * Signature: ([BII[B)V
 */
JNIEXPORT void JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_rgbToYuv
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    rgbaToI420
 * Signature: ([BIIII[B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_rgbaToI420
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_cmbc_av_jni_ImageFormatUtils
 * Method:    RgbaToI420
 * Signature: (I[B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_cmbc_av_jni_ImageFormatUtils_RgbaToI420
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
